# Nom du projet
name: 'analyse_airbnb'
version: '1.0.0'
config-version: 2
dbt-cloud:
  project-id: 70471823551330

# Profil utilisé (correspond au nom dans profiles.yml)
profile: 'analyse_airbnb'

# Dossiers du projet

analysis-paths: ["analyses"]
macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
target-path: "target"
test-paths: ["tests"]

# Dossier de destination des fichiers compilés

clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des modèles
models:
  analyse_airbnb:
    # Configuration pour les modèles dans le dossier exemple
    example:
      +materialized: view

    # Configuration pour nos futurs modèles
    curation:
      +materialized: view
      +schema: curation

    analytics:
      +materialized: table
      +schema: analytics

# Configuration des seeds
seeds:
  analyse_airbnb:
    +enabled: true
    +schema: raw

# Variables du projet
vars:
  # Variables pour les modèles incrémentaux (Chapitre 7)
  inc_database: 'airbnb'
  inc_schema: 'incremental'